# ./docker-compose.yml

version: '3'

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: rectask
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - ./:/var/www/html/
      - /var/www/html/vendor
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    links:
      - database:localhost
